### ISSUE TITLE
[Howto] Specific type (boolean, etc.)

### ISSUE THREAD

**Issue by kei-ix** [benwinding/react-admin-import-csv#16]
Hi,

Nice work!! You saved me time! I'm new in React and I'm working on a side project to develop a small admin interface above my own API.

I have a small question: is it possible to import via CSV specific type, like boolean ?

Thank you !

**Comment by VicenteVicente** [comment]
Hi!, you could use the papaparse's parseConfig `dynamicTyping: true`. It parses **numbers** and **booleans** automaticly. For example:

```
const config = {
    parseConfig: {
      dynamicTyping: true,
  }
```

and then:

`<ImportButton {...config} />`

**Comment by kei-ix** [comment]
I checked on Papaparse's documentation, according to your comment and I found the solution: `dynamicTyping: true` 🥳 

Thank you very much for your help !
