### ISSUE TITLE
Custom importer function

### ISSUE THREAD

**Issue by enricodeleo** [benwinding/react-admin-import-csv#20]
Is it possible to inject a custom importer function the same way we do for `exporter`?

**Comment by benwinding** [comment]
Hi @enricodeleo,

What do you mean by _exporter_? We have the following options available to use:

``` tsx
const config: ImportConfig = {
  // A function to translate the CSV rows on import 
  preCommitCallback?: (action: "create" | "overwrite", values: any[]) => any[];
  // A function to handle row errors after import
  postCommitCallback?: ([]) => any[];
}
```
``` jsx
<ImportButton {...props} {...config}/> 
```

Any other functionality, you're better off manipulating your dataprovider.

Cheers,
Ben

**Comment by enricodeleo** [comment]
Thanks for your reply @benwinding
