### ISSUE TITLE
Minimize HTTP requests

### ISSUE THREAD

**Issue by fzaninotto** [benwinding/react-admin-import-csv#21]
Hi, and thanks for sharing this module, it's really helpful. 

I have a concern with the way you send the imported records to the backend (using a list of `create` calls). This is not efficient from a network point of view, and can even be seen as a DoS from the backend.

May I suggest you call a new verb on the dataProvider (something like `createMany`), and leave the implementation to the developers? That way, if their API allows a single call to create many records, they can optimize the call. 

I also have a concern about the create / update choice un the UI. In my opinion, the button should be smarter, and detect the records that are already present (using a getMany), then update those and create the remaining ones. The option in the dialog should disappear, and only be shown if necessary (just like the file copy dialog in your system asks for a confirmation to ignore, update, or stop in that case).

Finally, I suggest that clicking on the "import" button opens the file selector right away. The file format (csv/tsv) can be enforced by a type attribute in the file input, and the presence of an id column can be checked a posteriori. 

These limitations are kind of blockers for me. Is there a chance that you implement these in your module, or should I redevelop another module on my side?

**Comment by benwinding** [comment]
Hi @fzaninotto,

> May I suggest you call a new verb on the dataProvider (something like createMany), and leave the implementation to the developers? That way, if their API allows a single call to create many records, they can optimize the call.

Yes, this makes way more sense, I will implement this.

> I also have a concern about the create / update choice un the UI. In my opinion, the button should be smarter, and detect the records that are already present (using a getMany), then update those and create the remaining ones. The option in the dialog should disappear, and only be shown if necessary (just like the file copy dialog in your system asks for a confirmation to ignore, update, or stop in that case).

So if I understand correctly, do you mean make a single import button, and when you click import it has another confirmation dialogue if there's records that will be overwritten?

> Finally, I suggest that clicking on the "import" button opens the file selector right away. The file format (csv/tsv) can be enforced by a type attribute in the file input, and the presence of an id column can be checked a posteriori.

Yes, this would make it quicker too. So clicking the import button would launch the file picker and then validate the CSV then continue if the CSV is valid, right?

> These limitations are kind of blockers for me. Is there a chance that you implement these in your module, or should I redevelop another module on my side?

Yes, I'll implement these and incrementally release the changes. Let me know if there's any issues with my responses above.

Also, I really love your work on `react-admin`, it's honestly one of the best frameworks I've ever worked with!

Cheers,
Ben

**Comment by fzaninotto** [comment]
About the UX, here is how I see it:

1. The user clicks on the import button
2. right away, the file selector appears. It only shows csv, tsv, and xls files
3. The user selects a file and submits. A dialog appears explaining that the import is in progress
4. your plugin processes the file client-side and checks that it can CSV decode it and that records have an id column. If it's not the case, show an error message in the dialog and let the user close it.
5. your plugin calls dataProvider.getMany() with the list of ids to see if some of the imported records are already present in the database. If it's the case, it displays a mention in the dialog: XX imported records already exist in the XX resource. What do you want to do with them? And the user can choose Ignore, Update, or Dismiss. If they dismiss, the dialog closes.
6. If the user chooses Ignore, then only the records not in the resource are imported. If they choose update, the plugin creates the non-existing records and updates the existing ones. During that process, the dialog remains open and shows a spinner.
7. When the import is complete, the dialog updates and shows how many records were imported. The user can close it, and the list should be refreshed by now.

**Comment by Odonno** [comment]
@benwinding Long time no see. Great job about the improvements on this library BTW!

@fzaninotto We already discussed some of those questions long ago on this issue #5 But from your new point of view and from what I already experienced, I think we should focus on how to make it simple stupid:

* Clean UX with a direct file selector. I am ok with this, it is the basic entry point
* The call to `getMany` seems like a good idea. Not sure why we didn't think about it. So you get two separate arrays of X new items to add and Y existing items to update. And maybe you can filter the Y items to see if anything change on each item (like a `distinct`) at this stage.
* On your point 5, I believe the user have two choices: Execute or Dismiss. In case of the Execute, I think that providing two checkboxes `Import new items` and `Update existing items`. By default, they are checked and the user can check/uncheck these based on what he want. And again, we display the number of X and Y items. So, if X or Y equals 0, the according checkboxes are hidden, no need to add useless inputs;
* On your point 6, we need to be clear about what we can do with the data provider. I agree that we should simplify the process at best with 1 call to `createMany` and 1 call to `updateMany`. Again, based on the user intent of course. I hope @benwinding can give insights on this too.
* And on your point 7, how would you do it? A dialog that recalls how many X and Y items were imported? A new page with all the items imported? Or maybe a link to this page? We can stay with a trival result of course. And I suppose the dialog should also handle error messages.

**Comment by fzaninotto** [comment]
I'm heavily inspired by File copy dialogs in Windows and MacOS, and I think your users will be used to them, too (because of [Jakob's law](https://lawsofux.com/jakobs-law.html). You should try to mimic these dialogs as much as possible, hence the idea to have 3 buttons: Ignore, Update, or Dismiss, instead of checkboxes.

When I'm talking about a dialog, it's the same one throughout the entire process. the content changes (loading -> ask about what to do for duplicates -> loading -> confirm, or loading -> invalid CSV).

**Comment by Odonno** [comment]
@fzaninotto I am not aware of an import Dialog anywhere in Windows.

**Comment by fzaninotto** [comment]
I'm talking about the file transfer dialog (here, in Windows)

![image](https://user-images.githubusercontent.com/99944/91173695-85caa580-e6de-11ea-9793-e7bbda9eebee.png)

**Comment by Odonno** [comment]
Oh ok. Well, files and data are not the same stuff IMO. But I suppose in term of simplicity you can insert new items by design and let user choose what to do with the already existing items. That seems fair to me.

**Comment by benwinding** [comment]
Hi @fzaninotto, @Odonno,
We finally have a working alpha release of the new import workflow, let me know what you think!

**Try live demo here:**
https://benwinding.github.io/react-admin-import-csv/#/posts

![Peek 2020-09-19 14-50](https://user-images.githubusercontent.com/11782590/93659721-83622e00-fa87-11ea-90c4-650aecf60a6a.gif)

**Try out `alpha-release` package here**
`npm install react-admin-import-csv/v/1.0.0-alpha.0`

All changes are in PR: #27

**Comment by fzaninotto** [comment]
Excellent, kudos for the great work!

I noticed the notification after the import shows tokens instead of values in the demo you linked.

![image](https://user-images.githubusercontent.com/99944/94770162-30a44280-03b4-11eb-8ddb-013c1c3c022d.png)

Is it a bug, or something that needs to be translated by the developer when using this package?

**Comment by benwinding** [comment]
Thanks @fzaninotto !
That was a `translation` bug, should be fixed now.
This library contains `i18n` translations for many languages (so the developer doesn't need to provide any), but some languages aren't finished (due to the upgrade). Refer to issue #30 for more details
