### ISSUE TITLE
preCommitCallback is ignored due to hooks setting values asynchronously

### ISSUE THREAD

**Issue by Mattia-Longhin** [benwinding/react-admin-import-csv#25]
Hello,

First of all, thank you for your work!

I think that there is an issue with `preCommitCallback`. You call `setValues` with the result of `preCommitCallback` and then you use the content of `values` variable directly. 

This does not work because you cannot trust `setValues` to synchronously change `values`. Your are providing the old values to the `create` function. 

https://github.com/benwinding/react-admin-import-csv/blob/ece80b9a103c25b5ec130e5c0ce45900613cbcf5/src/import-csv-button.tsx#L101

**Comment by benwinding** [comment]
Thanks for reporting and fixing the issue!
Closed by #26
