### ISSUE TITLE
Missing lib/ folder

### ISSUE THREAD

**Issue by Pierre-Demessence** [benwinding/react-admin-import-csv#32]
Hello,

I tried updating to **1.0.3** from **0.2.18** but I'm then unable to resolve imports due to a missing `lib/` folder.
> Module not found: Can't resolve 'react-admin-import-csv' in '...'

Here's the file structure in `node_modules/react-admin-import-csv` in 0.2.18 (and 0.2.20).
![image](https://user-images.githubusercontent.com/1756398/95114363-1a93da80-0744-11eb-9794-8d72faa762a1.png)

Here's the file structure in `node_modules/react-admin-import-csv` in 1.0.3 (and 1.0.2).
![image](https://user-images.githubusercontent.com/1756398/95114795-c3dad080-0744-11eb-85b9-732dac489009.png)

**Comment by Pierre-Demessence** [comment]
After trying all the versions one by one, it seems the change happened between 1.0.1 (which has the lib/ folder) and 1.0.2 (which doesn't have it).

**Comment by benwinding** [comment]
Thanks for reporting the issue @Pierre-Demessence,
This was an issue with the Github Actions deployment.
It's now fixed by commit: 4c7647a8afe4987b5455e007738e4d805348d1ac 
Should be released in `react-admin-import-csv@1.0.4`
Cheers,
Ben
