### ISSUE TITLE
postCommitCallback always receives empty array for creation

### ISSUE THREAD

**Issue by fzaninotto** [benwinding/react-admin-import-csv#34]
```jsx
<ImportButton
                resource={resource}
                postCommitCallback={reportItems =>
                    console.log('reportItems', reportItems)
                }
            />
```

Always logs an empty array (`[]`).

I suspect that's because `createInDataProvider` never updates the `reportItems` in

https://github.com/benwinding/react-admin-import-csv/blob/b8e2f79393d480e4c7278ea33d13283500297a24/src/uploader.ts#L68-L94

**Comment by benwinding** [comment]
Thanks @fzaninotto,
Should be fixed now, returning the report items array from `createInDataProvider` 
Cheers,
Ben
