### ISSUE TITLE
Unexpected behaviour on import with dynamicTyping

### ISSUE THREAD

**Issue by peter-jerry-ye** [benwinding/react-admin-import-csv#45]
Sorry to disturb you again, but I've found this:

If you change your example `posts.js` to:
```javascript
const ListActions = (props) => {
  const {
    className,
    basePath,
    total,
    resource,
    currentSort,
    filterValues,
    exporter,
  } = props;
  const config = {
    logging: true,
    validateRow: async (row) => {
      if (row.id) {
        // throw new Error("AAAA");
      }
    },
  };
  return (
    <TopToolbar className={className}>
      <CreateButton basePath={basePath} />
      <ExportButton
        disabled={total === 0}
        resource={resource}
        sort={currentSort}
        filter={filterValues}
        exporter={exporter}
      />
      <ImportButton {...props} {...config} parseConfig={{dynamicTyping: true}}/>
    </TopToolbar>
  );
};
``` 
i.e. delete postCommitCallback and add this parseConfig, when you import data with conflicting ids, it will not show the dialog but quit directly. Is it an expected behaviour? Thanks.

**Comment by benwinding** [comment]
Hi @peter-jerry-ye,
No that's not expected behaviour thanks for reporting it. Hmm it's probably to do with the comparison here, it uses values from your dataprovider to compare to the ID's imported in the CSV. This will not detect a colliding ID if the dataprovider returns an id with type `number`...

https://github.com/benwinding/react-admin-import-csv/blob/a07aec59d258a9652061ab662df8b665f54b4743/src/import-controller.ts#L25-L30

Perhaps we should compare for colliding ID's like this:
``` js
const matchesAsNumbers = parseInt(id1) + parseInt(id2)
const matchesAsStrings = ''+id1 + ''+id2
const matches = matchesAsNumbers || matchesAsStrings
```

**Comment by peter-jerry-ye** [comment]
There are multiple choices.
- You can convert them all to string when comparaison, as I proposed in #46 .
- You can type check them and use correct comparaison
- You may just leave id as it is in [line 29](https://github.com/benwinding/react-admin-import-csv/blob/a07aec59d258a9652061ab662df8b665f54b4743/src/import-controller.ts#L29). `recordsColliding.data.map((r) => r.id)`. Perhaps you can provide a tye parameter for id somewhere.
- You may leave it as it is, just indicate this issue in the `README`, and I shall convert my input with `preCommitCallback`.

By the way, maybe \`${r.id}\` is more succint than `r.id + '' as string` :grinning:

Have a good night

**Comment by benwinding** [comment]
> You can convert them all to string when comparaison, as I proposed in #46 .

To me this is the best option:
- The only problem I can see is which `ID` should be sent to the DataProvider?
- If `id1 = 2` and `id2 = '2'` these will become equivalent, so should it always pick the ID from the DataProvider?

> By the way, maybe \`${r.id}\` is more succint than `r.id + '' as string` :grinning:

That's debatable lol, I personally think `r.id + ''` is clearer _(you don't need the `as string` either)_

Cheers,
Ben

**Comment by peter-jerry-ye** [comment]
> * The only problem I can see is which `ID` should be sent to the DataProvider?

It seems to me it is best to send whatever the user give you, i.e. the parse result from csv, so that the user can have full control. That being said, in the definition of `Identifier` is `string | number`, so you can send string. Just mark it in the `README` if you always send a string in case they put `identifier as number` somewhere in code.

> * If `id1 = 2` and `id2 = '2'` these will become equivalent, so should it always pick the ID from the DataProvider?

I do expect the type in the parse result corresponding to the type from the DataProvider, which is both number in your case. If the type is different but the value is the same, I think it could be safe to say it's just a type issue: there's hardly anyone uses two types to define a single table column.

**Comment by benwinding** [comment]
Hey @peter-jerry-ye, I've just merged it in.

Have a test and let me know if there's any issues.

Also, what dataprovider are you using in your project? just curious
