### ISSUE TITLE
Customizable/override collistion detection code

### ISSUE THREAD

**Issue by fkowal** [benwinding/react-admin-import-csv#52]
Hey

I ran into an issue with collision detection

I export data using the build in `Export` the `Import` using your plugin

And here is what happens

```logger.log("Has colliding ids?", { hasCollidingIds, collidingIds });```
shows that all Ids this makes sense because i exported the data from the system

So this works fine

But the 
```
logger.log("Importing items which arent colliding", {
        csvItemsNotColliding,
      });
```
Sadly show the very same Ids as the colliding Ids

And the end result is the the same set of data is passed to `create` and then to `update`

So i'd like to propose adding a `config: {partition: (csv[]) => [[rows2Create], [rows2Update]]`

The end goal here would be to give the user control of what goes into `create` and what goes to `update`

**Comment by benwinding** [comment]
Seems I can't seem to replicate this issue, on the demo site here: https://benwinding.github.io/react-admin-import-csv

Can you show me how to recreate the issue?

**Comment by fkowal** [comment]
ok i found the cause

```
const collidingIdsStringsSet = new Set(["x","z"])
const collidingIdsNumbersSet = new Set([1,2])
function idNotInNumbersOrStrings(item) {
        const matchesIdString = !collidingIdsStringsSet.has(item.id+'')
        const matchesIdNumber = !collidingIdsNumbersSet.has(+item.id)
        return matchesIdNumber || matchesIdString;
}

idNotInNumbersOrStrings({id:"x"}) // true
idNotInNumbersOrStrings({id:"y"}) // true
```

this methods always returns true for the "other" type
because of ```!collidingIdsNumbersSet.has(+item.id)``` always returns true
