### ISSUE TITLE
Latest version is not available on npm/yarn

### ISSUE THREAD

**Issue by bertrandjamin** [benwinding/react-admin-import-csv#56]
Hi, 

I would like to use the latest version of your lib (notably the updateManyArray workaround cf #55 ). 

But when I retrieve it  from yarn I have an older version 🤔 

The documentation here https://www.npmjs.com/package/react-admin-import-csv without the referenece to `updateManyArray` seems to confirm this.

Thanks !

**Comment by benwinding** [comment]
Sorry about that, the deployment wasn't triggered, should be deployed now as `v1.0.16`.

**Comment by bertrandjamin** [comment]
Oh yes sorry I haven't realized that it was not yet released :/ 

Thank you for your quick answer !
