### ISSUE TITLE
Issue with the resource post count when importing records

### ISSUE THREAD

**Issue by vinodphadtare** [benwinding/react-admin-import-csv#66]
When I tried to import records using demo app with this CSV 
[posts.csv](https://github.com/benwinding/react-admin-import-csv/files/6383988/posts.csv)

Although CSV contains 4 records but message is display as 5 records.
![incorrect-row-count](https://user-images.githubusercontent.com/12867429/116230997-f1857680-a775-11eb-8cff-346b5ec71462.png)

After clicking on "Let me decide for each row" count is displayed correct.

**Comment by vinodphadtare** [comment]
I tried to debug this issue, I am not sure why we are adding +1 for conflicting ids length

file: src/components/import-csv-dialog-strategy.tsx
line 66: 
`conflictingCount: idsConflicting && idsConflicting.length + 1,`

please suggest.

**Comment by benwinding** [comment]
Hi @vinodphadtare,
Thanks again for reporting the issue, yes it looks like this was a mistake, the +1 is not required. This change will be available in version `1.0.19`.
Cheers,
Ben
