### ISSUE TITLE
Import functionality with row by row is updating wrong record

### ISSUE THREAD

**Issue by vinodphadtare** [benwinding/react-admin-import-csv#67]
when I tried importing csv file 
[posts.csv](https://github.com/benwinding/react-admin-import-csv/files/6384009/posts.csv)

and selected "Let me decide for each row"
![Current Record](https://user-images.githubusercontent.com/12867429/116231478-8f794100-a776-11eb-8624-625085d94ac0.png)

Now you can see in console current record is with ID "4" But when I click "Replace the row ID =4" button, Code replaces record with ID=3 
![replaced-wrong-record](https://user-images.githubusercontent.com/12867429/116232023-3362ec80-a777-11eb-8a0f-ab062df9838e.png)

This happens with all the records when tried to replace or add new.

**Comment by vinodphadtare** [comment]
I was able to resolve this issue by changing two function in "src/main-csv-button.tsx" file

In handleAskDecideReplace, we should update to replace current record and then get nextConflicting record, instead of getting next conflicting record and updating it.
Original Code (line 229)
<pre>
const handleAskDecideReplace = async () => {
    logger.log("handleAskDecideReplace");
    const val = nextConflicting();
    if (!val) {
      return handleClose();
    }
    await updateRows([val]);
  };
</pre>
Updated Code
<pre>
const handleAskDecideReplace = async () => {
    logger.log("handleAskDecideReplace");
    await updateRows([currentValue]);
    const val = nextConflicting();
    if (!val) {
      return handleClose();
    }
  };
</pre>

similarly for handleAskDecideAddAsNew we need to create a localCopy of current record and add it, instead of next conflicting record.
original code(line 238)
<pre>
const handleAskDecideAddAsNew = async () => {
    logger.log("handleAskDecideAddAsNew");
    const val = nextConflicting();
    if (!val) {
      return handleClose();
    }
    delete val.id;
    await createRows([val]);
  };
</pre>

updated code
<pre>
const handleAskDecideAddAsNew = async () => {
    logger.log("handleAskDecideAddAsNew");
    const localCopy = Object.assign({},currentValue)
    delete localCopy.id;
    await createRows([localCopy]);
    const val = nextConflicting();
    if (!val) {
      return handleClose();
    }
  };
</pre>

**Comment by benwinding** [comment]
Hi @vinodphadtare,
Thanks for reporting the issue, I've updated with your changes and it will be available in the  `1.0.19`
Also, feel free to submit pull requests for bugs like this in the future!
Cheers,
Ben
