### ISSUE TITLE
Adding translation

### ISSUE THREAD

**Issue by awesome-michael** [benwinding/react-admin-import-csv#7]
Is it possible to make the strings used in your UI translateable?

**Comment by benwinding** [comment]
Hi @awesome-michael 
I'm not sure how to do that, do you have experience in this?

**Comment by awesome-michael** [comment]
Unfortunately I just used the translation instead of implementing it. Maybe these could be a starting point:

https://marmelab.com/react-admin/Translation.html#introducing-the-i18nprovider
https://marmelab.com/react-admin/Translation.html#translating-notification-messages

**Comment by mananomartinez** [comment]
@benwinding, great project. Saved me a lot of time. 
I need the same thing, plus a couple of other enhancements. I might be able to add the translation and make the changes I need.
Should I just do pull requests?

**Comment by benwinding** [comment]
Hey @mananomartinez,
Yeah send some Pull Requests through if you want, that would be great!
Cheers,
Ben

**Comment by mananomartinez** [comment]
Hey @benwinding , 

I have the code ready but don't seem to have permissions to push the new branch to this repo. Anything you can do on your end?

Thanks, 
Jose

**Comment by awesome-michael** [comment]
Afaik you have to fork the repo, push the branch into your own version of the repo and then file a PR out of that.

**Comment by mananomartinez** [comment]
Thanks @awesome-michael. I hadn't really contributed on a github project before. :) PRs are up

**Comment by benwinding** [comment]
Thanks @mananomartinez!
Yes, forking and making a PR that way is the standard approach for most github projects. I'll take a look at yours now.
Cheers,
Ben

**Comment by benwinding** [comment]
Closed by #10 #9
