### ISSUE TITLE
Is there a way to change the default tooltip? 

### ISSUE THREAD

**Issue by koaladlt** [benwinding/react-admin-import-csv#72]
Hey guys. So maybe I'm missing something in the docs, but I can't find a way to edit the default tooltip on the import button. Thanks in advance!

<img width="156" alt="Screen Shot 2021-09-06 at 16 57 53" src="https://user-images.githubusercontent.com/64273203/132257468-30c50d0f-97e6-4452-85b5-9349c5512056.png">

**Comment by benwinding** [comment]
That tooltip comes from this translation file

https://github.com/benwinding/react-admin-import-csv/blob/6b335e2a5b7f776724fc1086a45b15a5d6168702/src/i18n/en.ts#L2-L6

There's a spanish translation file for that too:

https://github.com/benwinding/react-admin-import-csv/blob/6b335e2a5b7f776724fc1086a45b15a5d6168702/src/i18n/es.ts#L2-L6

Follow the `i18n` translation help in the readme and let me know how you go 👍 
https://github.com/benwinding/react-admin-import-csv#translation-i18n

**Comment by koaladlt** [comment]
@benwinding Configuring the i18n did the trick, thank you so much!
