### ISSUE TITLE
change encoding

### ISSUE THREAD

**Issue by vahidqo** [benwinding/react-admin-import-csv#75]
Hi friends
When I import a CSV file that contains Persian letters, the letters will be converted to "????". I think the problem is in encoding.
I want to change the CSV encoding when uploading a file. How can I do this?

**Comment by benwinding** [comment]
Yeah interesting, you should be able to pass in the encoding string value to the papaparse options like this:

```
const importOptions = {
  parseConfig?: {
    encoding: 'ISO-8859-1'
  }
}
```

For all `parseConfig` options see: https://www.papaparse.com/docs#config
